### PR TITLE
Add a .queryParameterAs[TYPE] to HttpRequest

### PR DESCRIPTION
**Pull request by kaidamasaki**

### CODE REVIEW

**Comment by kaidamasaki** [comment]
@rjmac: I'm a little worried that unless I do something in `HttpRequest.scala` people will have to import `com.socrata.http.server.routing._` to be able to use this new method.

**Comment by rjmac** [comment]
They will not, as long as the `Extractor`s they want are defined in `Extractor`'s companion object (or the companion objects of the things they're trying to extract).

**Comment by catstavi** [comment]
If this does block compilation when you request a parameter as a type it doesn't understand, then I think this is great!

**Comment by kaidamasaki** [comment]
Damn, bad timing with your comment. Yes, it does, I confirmed with Robert.

**Pull request merged**
